### ISSUE TITLE
some dashboards are showing no datapoints

### ISSUE THREAD

**Issue by Murryy79** [vmware-archive/prometheus-on-PCF#12]
some dashboards showing no datapoints at all
![image](https://user-images.githubusercontent.com/19574664/29382358-f7921810-8291-11e7-80ab-714dba2f980c.png)

![image](https://user-images.githubusercontent.com/19574664/29382391-0a82ab38-8292-11e7-89df-d458b44043b3.png)

System overview not showing all VMS
![image](https://user-images.githubusercontent.com/19574664/29382439-2e711264-8292-11e7-9370-a95918213eec.png)

am I serioulsly missing anything thats why dashboards are not showing any datapoints?
some dashboards are just fine
![image](https://user-images.githubusercontent.com/19574664/29382529-69201e50-8292-11e7-99c6-862de3164c7d.png)

do i need to configure datasource like influxDB? why?

**Comment by mkuratczyk** [comment]
Hi. There are three data sources that are used to monitor PCF - bosh_exporter, firehose_exporter and cf_exporter. Different graphs use values emitted by different exporters so a situation where you see data in some dashboards but not others typically means that some exporters are running fine while other don't. I'd start by going to each exporters logs: on the Prometheus VM go to /var/vcap/sys/log and check bosh_exporter/* cf_exporter/*  and firehose_exporter/*.

**Comment by mkuratczyk** [comment]
Oh, and regarding InfluxDB - it's not needed at all. What made you think it could be required?

**Comment by Murryy79** [comment]
@mkuratczyk Thanks again. your quick response much appreciated. I did check logs for cf_exporter and found 
time="2017-08-16T20:35:51Z" level=error msg="Error while listing `audit.app.update` application events: Error requesting appevents Get https://api.system.cf-ssb-z3-dev.discoverfinancial.com/v2/events?q=type:audit.app.update: oauth2: cannot fetch token: 401 Unauthorized\nResponse: {\"error\":\"unauthorized\",\"error_description\":\"**Bad credentials**\"}" source="application_events_collector.go:188"

I thought I was using the correct credentials , but anyways I reset uaac client prometheus secret using following
uaac secret set prometheus-cf

That error stopped throwing in the logs and cf-summary dashboard started showing data ...

stumbled on some link on google about influxDB so was asking if that was related to my dashboards not showing data.

**Comment by mkuratczyk** [comment]
Influxdb_exporter (which is a fake API-compatible server that pretends to be InfluxDB but exposes data for Prometheus instead of actually storying it) or an actual InfluxDB (a different BOSH release) can be used to monitor Concourse. There is one dashboard for Concourse monitoring in prometheus-boshrelease but if you want a more detailed view of your Concourse I'd currently recommend deploying an actual InfluxDB (problem is Concourse emits events which are not handled well by Prometheus). You can see an example of Concourse dashboards with real InfluxDB on https://metrics.concourse.ci/
