### ISSUE TITLE
Grafana not starting on v18.6.0

### ISSUE THREAD

**Issue by PlatOps** [vmware-archive/prometheus-on-PCF#13]
We had Prometheus v17.6.1 running fine on stemcell 3363.26. Tried to update it to v18.6.0 on stemcell 3363.31. But grafana fails to start even after recreating the VM

 Failed: Action Failed get_task: Task 84966960-8a63-4dec-54c4-9cd3edfd0825 result: 1 of 1 post-start scripts failed. Failed Jobs: grafana. (00:01:49)

Error 100: Error resolving problem '141': Action Failed get_task: Task 84966960-8a63-4dec-54c4-9cd3edfd0825 result: 1 of 1 post-start scripts failed. Failed Jobs: grafana.

**Comment by mkuratczyk** [comment]
Please provide /var/vcap/sys/log/post-start* and recent logs from /var/vcap/sys/log/grafana/* from Grafana VM. There were indeed changes to the post-start script in this release so perhaps we missed something.

**Comment by mkuratczyk** [comment]
Correction: /var/vcap/sys/log/grafana/post-start*.

**Comment by PlatOps** [comment]
Michal – Attached are the requested logs. It’s all in the same file since the size is very small.

Thanks
Simmy

**Comment by PlatOps** [comment]
grafana/f80d0291-a561-47a4-8e7f-987cff89dd69:~# ls -l /var/vcap/sys/log/
total 40
drwxr-x--- 2 vcap vcap 4096 Sep  8 19:44 clamav
drwxr-xr-x 2 vcap vcap 4096 Sep  8 19:44 fim
drwxr-xr-x 2 root root 4096 Sep  8 19:44 grafana
-rw-r--r-- 1 root root  108 Sep  8 19:44 grafana_ctl.err.log
-rw-r--r-- 1 root root  108 Sep  8 19:44 grafana_ctl.log
drwxr-xr-x 2 root root 4096 Sep  8 19:44 monit
drwxr-xr-x 2 root root 4096 Sep  8 19:44 node_exporter
-rw-r--r-- 1 root root  114 Sep  8 19:44 node_exporter_ctl.err.log
-rw-r--r-- 1 root root  114 Sep  8 19:44 node_exporter_ctl.log
drwxr-xr-x 3 root root 4096 Sep  8 19:44 syslog_forwarder
grafana/f80d0291-a561-47a4-8e7f-987cff89dd69:~# cd /var/vcap/sys/log/grafana
grafana/f80d0291-a561-47a4-8e7f-987cff89dd69:/var/vcap/sys/log/grafana# ls -l
total 16
-rw-r--r-- 1 root root 4051 Sep  8 19:44 grafana.log
-rw-r--r-- 1 root root    0 Sep  8 19:44 grafana.stderr.log
-rw-r--r-- 1 root root 3384 Sep  8 19:44 grafana.stdout.log
-rw-r----- 1 root root   87 Sep  8 19:44 post-start.stderr.log
-rw-r----- 1 root root 1092 Sep  8 19:44 post-start.stdout.log
grafana/f80d0291-a561-47a4-8e7f-987cff89dd69:/var/vcap/sys/log/grafana# cat grafana.log
t=2017-09-08T19:44:11+0000 lvl=info msg="Starting Grafana" logger=main version=4.3.2 commit=ed4d170 compiled=2017-05-31T08:48:16+0000
t=2017-09-08T19:44:11+0000 lvl=info msg="Config loaded from" logger=settings file=/var/vcap/packages/grafana/conf/defaults.ini
t=2017-09-08T19:44:11+0000 lvl=info msg="Config loaded from" logger=settings file=/var/vcap/jobs/grafana/config/grafana.ini
t=2017-09-08T19:44:11+0000 lvl=info msg="Path Home" logger=settings path=/var/vcap/packages/grafana
t=2017-09-08T19:44:11+0000 lvl=info msg="Path Data" logger=settings path=/var/vcap/store/grafana
t=2017-09-08T19:44:11+0000 lvl=info msg="Path Logs" logger=settings path=/var/vcap/sys/log/grafana
t=2017-09-08T19:44:11+0000 lvl=info msg="Path Plugins" logger=settings path=/var/vcap/packages/grafana_plugins
t=2017-09-08T19:44:11+0000 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
t=2017-09-08T19:44:11+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2017-09-08T19:44:11+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account to org"
t=2017-09-08T19:44:11+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account to org"
t=2017-09-08T19:44:11+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account_user to org_user"
t=2017-09-08T19:44:11+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account_user to org_user"
t=2017-09-08T19:44:11+0000 lvl=info msg="Creating json dashboard index for path: /var/vcap/store/grafana/dashboards"
t=2017-09-08T19:44:11+0000 lvl=info msg="Ldap enabled, reading config file" logger=ldap file=/var/vcap/jobs/grafana/config/ldap.toml
t=2017-09-08T19:44:11+0000 lvl=info msg="Starting plugin search" logger=plugins
t=2017-09-08T19:44:11+0000 lvl=info msg="Registering plugin" logger=plugins name="Status Panel"
t=2017-09-08T19:44:11+0000 lvl=info msg="Registering plugin" logger=plugins name=Clock
t=2017-09-08T19:44:11+0000 lvl=info msg="Registering plugin" logger=plugins name=Diagram
t=2017-09-08T19:44:11+0000 lvl=info msg="Registering plugin" logger=plugins name=Histogram
t=2017-09-08T19:44:11+0000 lvl=info msg="Registering plugin" logger=plugins name="Pie Chart"
t=2017-09-08T19:44:11+0000 lvl=info msg="Registering plugin" logger=plugins name="Worldmap Panel"
t=2017-09-08T19:44:11+0000 lvl=eror msg="Plugins: Failed to load plugin json file: /var/vcap/data/packages/grafana_plugins/3ab1f3e46cae5f1f7c7d9644bee14faebfcebf1a/worldping-app/dist/grafana-worldmap-panel/plugin.json,  err: Plugin with same id already exists"
t=2017-09-08T19:44:11+0000 lvl=info msg="Registering plugin" logger=plugins name="worldPing CTA"
t=2017-09-08T19:44:11+0000 lvl=info msg="Registering plugin" logger=plugins name="worldPing Endpoint List"
t=2017-09-08T19:44:11+0000 lvl=info msg="Registering plugin" logger=plugins name="worldPing Endpoint Nav"
t=2017-09-08T19:44:11+0000 lvl=info msg="Registering plugin" logger=plugins name=worldPing
t=2017-09-08T19:44:11+0000 lvl=info msg="Initializing Alerting" logger=alerting.engine
t=2017-09-08T19:44:11+0000 lvl=info msg="Initializing CleanUpService" logger=cleanup
t=2017-09-08T19:44:11+0000 lvl=info msg="Initializing Stream Manager"
t=2017-09-08T19:44:11+0000 lvl=info msg="Initializing HTTP Server" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
t=2017-09-08T19:44:30+0000 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
t=2017-09-08T19:44:30+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2017-09-08T19:44:30+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account to org"
t=2017-09-08T19:44:30+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account to org"
t=2017-09-08T19:44:30+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account_user to org_user"
t=2017-09-08T19:44:30+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account_user to org_user"
grafana/f80d0291-a561-47a4-8e7f-987cff89dd69:/var/vcap/sys/log/grafana# cat grafana.stdout.log
t=2017-09-08T19:44:11+0000 lvl=info msg="Starting Grafana" logger=main version=4.3.2 commit=ed4d170 compiled=2017-05-31T08:48:16+0000
t=2017-09-08T19:44:11+0000 lvl=info msg="Config loaded from" logger=settings file=/var/vcap/packages/grafana/conf/defaults.ini
t=2017-09-08T19:44:11+0000 lvl=info msg="Config loaded from" logger=settings file=/var/vcap/jobs/grafana/config/grafana.ini
t=2017-09-08T19:44:11+0000 lvl=info msg="Path Home" logger=settings path=/var/vcap/packages/grafana
t=2017-09-08T19:44:11+0000 lvl=info msg="Path Data" logger=settings path=/var/vcap/store/grafana
t=2017-09-08T19:44:11+0000 lvl=info msg="Path Logs" logger=settings path=/var/vcap/sys/log/grafana
t=2017-09-08T19:44:11+0000 lvl=info msg="Path Plugins" logger=settings path=/var/vcap/packages/grafana_plugins
t=2017-09-08T19:44:11+0000 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
t=2017-09-08T19:44:11+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2017-09-08T19:44:11+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account to org"
t=2017-09-08T19:44:11+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account to org"
t=2017-09-08T19:44:11+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account_user to org_user"
t=2017-09-08T19:44:11+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account_user to org_user"
t=2017-09-08T19:44:11+0000 lvl=info msg="Creating json dashboard index for path: /var/vcap/store/grafana/dashboards"
t=2017-09-08T19:44:11+0000 lvl=info msg="Ldap enabled, reading config file" logger=ldap file=/var/vcap/jobs/grafana/config/ldap.toml
t=2017-09-08T19:44:11+0000 lvl=info msg="Starting plugin search" logger=plugins
t=2017-09-08T19:44:11+0000 lvl=info msg="Registering plugin" logger=plugins name="Status Panel"
t=2017-09-08T19:44:11+0000 lvl=info msg="Registering plugin" logger=plugins name=Clock
t=2017-09-08T19:44:11+0000 lvl=info msg="Registering plugin" logger=plugins name=Diagram
t=2017-09-08T19:44:11+0000 lvl=info msg="Registering plugin" logger=plugins name=Histogram
t=2017-09-08T19:44:11+0000 lvl=info msg="Registering plugin" logger=plugins name="Pie Chart"
t=2017-09-08T19:44:11+0000 lvl=info msg="Registering plugin" logger=plugins name="Worldmap Panel"
t=2017-09-08T19:44:11+0000 lvl=eror msg="Plugins: Failed to load plugin json file: /var/vcap/data/packages/grafana_plugins/3ab1f3e46cae5f1f7c7d9644bee14faebfcebf1a/worldping-app/dist/grafana-worldmap-panel/plugin.json,  err: Plugin with same id already exists"
t=2017-09-08T19:44:11+0000 lvl=info msg="Registering plugin" logger=plugins name="worldPing CTA"
t=2017-09-08T19:44:11+0000 lvl=info msg="Registering plugin" logger=plugins name="worldPing Endpoint List"
t=2017-09-08T19:44:11+0000 lvl=info msg="Registering plugin" logger=plugins name="worldPing Endpoint Nav"
t=2017-09-08T19:44:11+0000 lvl=info msg="Registering plugin" logger=plugins name=worldPing
t=2017-09-08T19:44:11+0000 lvl=info msg="Initializing Alerting" logger=alerting.engine
t=2017-09-08T19:44:11+0000 lvl=info msg="Initializing CleanUpService" logger=cleanup
t=2017-09-08T19:44:11+0000 lvl=info msg="Initializing Stream Manager"
t=2017-09-08T19:44:11+0000 lvl=info msg="Initializing HTTP Server" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
grafana/f80d0291-a561-47a4-8e7f-987cff89dd69:/var/vcap/sys/log/grafana# cat post-start.stdout.log
[Fri Sep  8 19:44:30 UTC 2017] Resetting grafana admin password ...
t=2017-09-08T19:44:30+0000 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
t=2017-09-08T19:44:30+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2017-09-08T19:44:30+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account to org"
t=2017-09-08T19:44:30+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account to org"
t=2017-09-08T19:44:30+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account_user to org_user"
t=2017-09-08T19:44:30+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account_user to org_user"

Admin password changed successfully ✔

[Fri Sep  8 19:44:30 UTC 2017] Calling 'grafana-users' ...
[Fri Sep  8 19:44:30 UTC 2017] Calling 'prometheus-datasource' ...
{"id":1,"message":"Datasource updated","name":"prometheus"}
Updated datasource prometheus at Fri Sep  8 19:44:30 UTC 2017
[Fri Sep  8 19:44:30 UTC 2017] Calling 'prometheus-dashboards' ...
grafana/f80d0291-a561-47a4-8e7f-987cff89dd69:/var/vcap/sys/log/grafana# cat post-start.stderr.log
ls: cannot access /var/vcap/packages/bosh_dashboards/*.json: No such file or directory
grafana/f80d0291-a561-47a4-8e7f-987cff89dd69:/var/vcap/sys/log/grafana#

**Comment by PlatOps** [comment]
I even tried using the combination of Prometheus v17.6.1 and Stemcell 3363.31 and the same error. Deleted the VM and recreated using bosh cck and the same result with failed grafana job start.

**Comment by mkuratczyk** [comment]
That seems related to changes introduced in 17.0.0 when dashboards and alerts were moved from packages to jobs (see https://github.com/cloudfoundry-community/prometheus-boshrelease/releases/tag/v17.0.0). Please make sure dashboard/alerts paths in your manifest are correct for v17+.

**Comment by PlatOps** [comment]
Michal – Appreciate the direction and that suggestion did the trick. Changed the path from /var/vcap/packages/ to /var/vcap/jobs/ for Alerts and Dashboards and the deployment is successful now. Thanks for the prompt response and support in resolving the issue.

Thanks
Simmy

**Comment by mkuratczyk** [comment]
Happy to hear it works!
