### ISSUE TITLE
Ability to disable mysqld_exporter when leveraging RDS provided by cloudformation script

### ISSUE THREAD

**Issue by xyloman** [vmware-archive/prometheus-on-PCF#7]
Our AWS setup leverages an off platform RDS for bosh director and ERT.  Therefore, we need to turn off the mysqld_exporter configuration in the prometheus.yml file.

**Comment by mkuratczyk** [comment]
Hi. This repo is meant as a starting point and certainly doesn't cover all use cases. It is assumed that for real-world deployments you'd maintain a custom manifest anyway. We might change that one day by refactoring it using BOSH CLIv2 ops files similar to cf-deployment and bosh-deployment repos. For the time being you can use an ops file to delete the part you don't need. To do that, create remove-mysqld_exporter.yml with the following content:
- type: remove
  path: /instance_groups/name=prometheus/jobs/name=mysqld_exporter
And add '-o remove-mysqld_exporter.yml' to your 'bosh interpolate' or 'bosh deploy' (if using CLIv2) command.

Hope that helps,
